In [1]:
import pandas as pd
import numpy as n
import matplotlib.pyplot as m
import seaborn as s
%matplotlib inline

In [2]:
c=pd.read_csv("Classified Data",index_col=0)
d=pd.read_csv("Classified Data")

In [3]:
c.head()

WTT       PTI       EQW       SBI       LQE       QWG       FDJ  \
0  0.913917  1.162073  0.567946  0.755464  0.780862  0.352608  0.759697   
1  0.635632  1.003722  0.535342  0.825645  0.924109  0.648450  0.675334   
2  0.721360  1.201493  0.921990  0.855595  1.526629  0.720781  1.626351   
3  1.234204  1.386726  0.653046  0.825624  1.142504  0.875128  1.409708   
4  1.279491  0.949750  0.627280  0.668976  1.232537  0.703727  1.115596   

        PJF       HQE       NXJ  TARGET CLASS  
0  0.643798  0.879422  1.231409             1  
1  1.013546  0.621552  1.492702             0  
2  1.154483  0.957877  1.285597             0  
3  1.380003  1.522692  1.153093             1  
4  0.646691  1.463812  1.419167             1

In [4]:
df=d.drop(["Unnamed: 0","TARGET CLASS"],axis=1)
df

WTT       PTI       EQW       SBI       LQE       QWG       FDJ  \
0    0.913917  1.162073  0.567946  0.755464  0.780862  0.352608  0.759697   
1    0.635632  1.003722  0.535342  0.825645  0.924109  0.648450  0.675334   
2    0.721360  1.201493  0.921990  0.855595  1.526629  0.720781  1.626351   
3    1.234204  1.386726  0.653046  0.825624  1.142504  0.875128  1.409708   
4    1.279491  0.949750  0.627280  0.668976  1.232537  0.703727  1.115596   
5    0.833928  1.523302  1.104743  1.021139  1.107377  1.010930  1.279538   
6    0.944705  1.251761  1.074885  0.286473  0.996440  0.428860  0.910805   
7    0.816174  1.088392  0.895343  0.243860  0.943123  1.045131  1.146536   
8    0.776551  1.463812  0.783825  0.337278  0.742215  1.072756  0.880300   
9    0.772280  0.515111  0.891596  0.940862  1.430568  0.885876  1.205231   
10   1.284999  1.331018  0.618910  0.657017  1.037191  0.717346  0.778501   
11   1.064356  1.414885  0.896798  0.629088  1.447704  0.791923  0.921676   
12   0.682953  1.254723  0.998870  0.397701  1.011621  0.567863  1.335120   
13   0.953318  1.318987  0.562921  0.905503  1.248314  0.677795  1.017305   
14   0.801268  0.936390  0.696960  0.972440  0.851299  1.443119  1.194476   
15   1.061691  1.044892  0.599729  0.465285  0.930288  0.974341  1.213450   
16   0.715645  1.378594  0.997797  0.674996  1.228928  1.223293  0.589346   
17   0.899792  1.225875  1.330887  0.335989  1.273570  1.100361  1.019617   
18   0.883813  1.275891  0.924066  0.668814  1.269021  1.382093  0.728286   
19   0.768311  1.394304  0.823118  0.612072  1.267414  0.881943  1.104178   
20   1.252864  1.661820  0.922198  0.875100  1.413852  1.330486  0.897273   
21   0.612488  1.338981  1.072606  0.799193  0.722667  1.139863  0.952153   
22   0.661652  0.603561  0.884153  0.484525  0.832281  1.094654  1.156142   
23   1.277638  0.925003  0.170924  1.057583  0.995938  0.934053  0.877794   
24   1.109953  1.363461  0.647339  0.368138  1.340851  1.088502  1.071250   
25   0.576839  1.319069  1.115112  1.131965  1.512161  0.954664  1.101880   
26   0.855927  0.859602  0.834234  0.905675  1.187995  1.398766  0.907756   
27   0.912403  0.935639  0.527303  0.669538  0.979297  0.769600  0.534440   
28   0.677778  1.040820  0.655777  0.479425  1.119399  1.226695  0.971849   
29   1.393081  1.193559  0.766170  0.961150  1.225038  1.129904  0.634757   
..        ...       ...       ...       ...       ...       ...       ...   
970  0.633387  1.004500  1.248108  1.059318  1.301176  0.913190  1.027950   
971  0.356470  1.182657  0.672876  1.068392  0.531516  1.254725  1.256490   
972  1.142004  1.194030  1.299440  0.736344  1.411419  0.961965  0.750759   
973  0.335992  1.343007  0.826096  0.843359  0.957316  0.879287  1.300711   
974  0.804679  0.737121  0.332621  0.666363  1.018735  0.688024  1.296284   
975  1.597781  0.927659  0.554321  0.750673  0.902208  0.984784  1.341203   
976  0.876415  0.839314  1.179024  0.255085  1.439665  0.826521  0.731261   
977  0.921677  1.361663  1.259150  0.649922  1.370695  1.405885  1.084434   
978  0.372314  0.975962  0.549580  0.519043  1.156110  1.103559  1.218810   
979  1.407042  0.999632  0.414295  0.598367  1.170322  1.001342  0.831199   
980  0.888072  0.757363  1.427844  0.841364  1.203507  0.784256  0.738744   
981  1.174795  1.018376  0.696083  0.269121  1.115722  1.526139  1.003034   
982  0.935199  0.796759  0.803251  0.684983  1.081238  0.824708  0.772558   
983  1.260558  0.610045  0.578569  0.524584  1.121035  0.737434  1.201745   
984  0.961599  1.122676  0.231524  0.866719  1.385338  0.885569  0.704372   
985  1.150205  0.726369  0.858908  0.750856  0.639816  0.495082  0.816259   
986  0.335641  1.078280  0.961443  0.621197  1.294154  1.287877  0.847741   
987  0.857298  0.759034  0.805310  0.634149  1.037998  0.824160  0.857125   
988  0.612156  1.354874  1.147571  0.734393  1.308312  1.048704  0.906302   
989  0.480687  1.240192  0.754194  0.804619  1.332328  0.893437  1.079114   
990  0

In [5]:
from sklearn.preprocessing import StandardScaler as scaler
from sklearn.preprocessing import scale as st

In [6]:
s=scaler()

In [7]:
s.fit(d.drop("TARGET CLASS",axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

#### finding standardization

In [8]:
scaled_features=s.transform(d.drop("TARGET CLASS",axis=1))

In [9]:
st(d.drop("TARGET CLASS",axis=1))

array([[-1.73031962, -0.12354188,  0.18590747, ..., -1.48236813,
        -0.9497194 , -0.64331425],
       [-1.72685552, -1.08483602, -0.43034845, ..., -0.20224031,
        -1.82805088,  0.63675862],
       [-1.72339142, -0.78870217,  0.33931821, ...,  0.28570652,
        -0.68249379, -0.37784986],
       ...,
       [ 1.72339142,  0.64177714, -0.51308341, ..., -2.36249443,
        -0.81426092,  0.11159651],
       [ 1.72685552,  0.46707241, -0.98278576, ..., -0.03677699,
         0.40602453, -0.85567   ],
       [ 1.73031962, -0.38765353, -0.59589427, ..., -0.56778932,
         0.3369971 ,  0.01034996]])

In [10]:
from sklearn.model_selection import train_test_split as t

In [11]:
from sklearn.neighbors import KNeighborsClassifier as k
from sklearn.metrics import confusion_matrix as c
from sklearn.metrics import accuracy_score as a
from sklearn.preprocessing import scale as s

In [12]:
x=st(d.drop("TARGET CLASS",axis=1))
y=d["TARGET CLASS"]

In [13]:
xtr,xte,ytr,yte=t(x,y,test_size=0.1,random_state=0)

In [14]:
knn=k(n_neighbors=1)

In [15]:
knn.fit(xtr,ytr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [16]:
pred=knn.predict(xte)

In [17]:
pred

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0], dtype=int64)

In [18]:
c(yte,pred)

array([[35,  9],
       [ 6, 50]], dtype=int64)

In [19]:
a(yte,pred)

0.85