In [1]:
import pandas as pd
import numpy as n
import matplotlib.pyplot as m
import seaborn as s
%matplotlib inline

In [2]:
c=pd.read_csv("Classified Data",index_col=0)
d=pd.read_csv("Classified Data")

In [3]:
c.head()

WTT       PTI       EQW       SBI       LQE       QWG       FDJ  \
0  0.913917  1.162073  0.567946  0.755464  0.780862  0.352608  0.759697   
1  0.635632  1.003722  0.535342  0.825645  0.924109  0.648450  0.675334   
2  0.721360  1.201493  0.921990  0.855595  1.526629  0.720781  1.626351   
3  1.234204  1.386726  0.653046  0.825624  1.142504  0.875128  1.409708   
4  1.279491  0.949750  0.627280  0.668976  1.232537  0.703727  1.115596   

        PJF       HQE       NXJ  TARGET CLASS  
0  0.643798  0.879422  1.231409             1  
1  1.013546  0.621552  1.492702             0  
2  1.154483  0.957877  1.285597             0  
3  1.380003  1.522692  1.153093             1  
4  0.646691  1.463812  1.419167             1

In [4]:
df=d.drop(["Unnamed: 0","TARGET CLASS"],axis=1)
df.head()

WTT       PTI       EQW       SBI       LQE       QWG       FDJ  \
0  0.913917  1.162073  0.567946  0.755464  0.780862  0.352608  0.759697   
1  0.635632  1.003722  0.535342  0.825645  0.924109  0.648450  0.675334   
2  0.721360  1.201493  0.921990  0.855595  1.526629  0.720781  1.626351   
3  1.234204  1.386726  0.653046  0.825624  1.142504  0.875128  1.409708   
4  1.279491  0.949750  0.627280  0.668976  1.232537  0.703727  1.115596   

        PJF       HQE       NXJ  
0  0.643798  0.879422  1.231409  
1  1.013546  0.621552  1.492702  
2  1.154483  0.957877  1.285597  
3  1.380003  1.522692  1.153093  
4  0.646691  1.463812  1.419167

In [5]:
from sklearn.preprocessing import StandardScaler as scaler
from sklearn.preprocessing import scale as st

In [6]:
s=scaler()

In [7]:
s.fit(d.drop("TARGET CLASS",axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

#### finding standardization

In [8]:
scaled_features=s.transform(d.drop("TARGET CLASS",axis=1))

In [9]:
st(d.drop("TARGET CLASS",axis=1))

array([[-1.73031962, -0.12354188,  0.18590747, ..., -1.48236813,
        -0.9497194 , -0.64331425],
       [-1.72685552, -1.08483602, -0.43034845, ..., -0.20224031,
        -1.82805088,  0.63675862],
       [-1.72339142, -0.78870217,  0.33931821, ...,  0.28570652,
        -0.68249379, -0.37784986],
       ...,
       [ 1.72339142,  0.64177714, -0.51308341, ..., -2.36249443,
        -0.81426092,  0.11159651],
       [ 1.72685552,  0.46707241, -0.98278576, ..., -0.03677699,
         0.40602453, -0.85567   ],
       [ 1.73031962, -0.38765353, -0.59589427, ..., -0.56778932,
         0.3369971 ,  0.01034996]])

In [10]:
from sklearn.model_selection import train_test_split as t

In [11]:
from sklearn.neighbors import KNeighborsClassifier as k
from sklearn.metrics import confusion_matrix as c
from sklearn.metrics import accuracy_score as a

In [12]:
x=df
y=d["TARGET CLASS"]

In [13]:
xtr,xte,ytr,yte=t(x,y,test_size=0.1,random_state=0)

In [14]:
knn=k(n_neighbors=1)

In [15]:
knn.fit(xtr,ytr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [16]:
pred=knn.predict(xte)

In [17]:
pred

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0], dtype=int64)

In [18]:
c(yte,pred)

array([[36,  8],
       [ 4, 52]], dtype=int64)

In [19]:
a(yte,pred)

0.88